name: Build & Release IntelliJ Plugin

# 可以手动触发或 push 到 main（你也可以改成其他分支）
on:
  workflow_dispatch:
  push:
    branches:
      - main

# 需要写入 repo contents（创建 release / 上传资产 / push tag）
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout repository (full history for tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Resolve version from Gradle
        id: get_version
        run: |
          # Try gradle properties output (works for Kotlin/Groovy builds if 'version' is set)
          VERSION_RAW=$(./gradlew properties -q | grep "^version:" | awk '{print $2}' || true)
          # fallback: try reading gradle.properties or build.gradle(.kts) (simple heuristics)
          if [ -z "$VERSION_RAW" ]; then
            if [ -f gradle.properties ]; then
              VERSION_RAW=$(grep "^version" gradle.properties | head -n1 | cut -d'=' -f2 | tr -d '[:space:]')
            fi
          fi
          if [ -z "$VERSION_RAW" ]; then
            # try common pattern in build.gradle(.kts)
            VERSION_RAW=$(grep -E "version\\s*=\\s*['\"]?[0-9]+\\.[0-9]+\\.[0-9]+" -m1 build.gradle* 2>/dev/null | sed -E "s/.*version\\s*=\\s*['\"]?([^'\" ]+)['\"]?.*/\\1/")
          fi
          if [ -z "$VERSION_RAW" ]; then
            echo "Could not detect project version. Set 'version' in build.gradle(.kts) or gradle.properties."
            exit 1
          fi
          VERSION=$(echo "$VERSION_RAW" | tr -d '[:space:]')
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build plugin (Gradle)
        run: ./gradlew clean buildPlugin

      - name: Determine tag name
        id: tag
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          # normalize tag with leading v
          if [[ "$VERSION" == v* ]]; then
            TAG="$VERSION"
          else
            TAG="v$VERSION"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "TAG=$TAG"

      - name: Ensure tag exists (create & push if missing)
        id: ensure_tag
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "Checking remote for tag $TAG ..."
          if git ls-remote --tags origin "$TAG" | grep -q "$TAG"; then
            echo "Tag $TAG already exists on remote. Skipping tag creation."
            echo "created=false" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist. Creating and pushing..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "$TAG" -m "Release $TAG"
            # push tag using repository token credentials (actions/checkout configured credentials by default)
            git push origin "$TAG"
            echo "created=true" >> $GITHUB_OUTPUT
          fi

      - name: Create or update GitHub Release and upload plugin ZIP
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output result
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          CREATED=${{ steps.ensure_tag.outputs.created }}
          echo "Release workflow finished for $TAG (tag_created=$CREATED)."
